### ISSUE TITLE
BioGateway Control panel names

### ISSUE THREAD

**Issue by makuintnu** [BioGateway/cytoscape-app#29]
![image](https://user-images.githubusercontent.com/17412163/82883793-39d35d80-9f43-11ea-8f03-60c74c7d4d00.png)
names of resources to change:
IntAct instead of Intact, multiple places
tfact2gene instead of Prot2Gene, multiple places
TFactS instead of TFacts
GEREDB instead of GREDB
HTRIdb instead of HTRI
ExTRI instead of EXTRI

**Comment by sholmas** [comment]
Updated the beta config to resolve this.
