### ISSUE TITLE
loading metadata

### ISSUE THREAD

**Issue by makuintnu** [BioGateway/cytoscape-app#38]
the loading of metadata becomes prohibitively slow when loading graphs of a couple of 100 nodes, not sure what can be done about it?
Of course you can disable metadata types, but if you need to add them anyway you have to wait for it at some point

**Comment by sholmas** [comment]
Unfortunately, there is no way to speed this up as of the way the app currently works. The metadata queries are executed independently of each other, as it is not cached anywhere (as opposed to names and definitions). The limitation is the speed of the SPARQL server, and its ability to process queries quickly. While executing queries in parallel would speed this up, it might overload the server if multiple users are doing it at the same time.

In the future, a redesign of the work flow with regards to metadata is probably worthwile.

**Comment by sholmas** [comment]
Closing this as it is no foreseeable solution to this issue. (Apart from caching it in the metadatabase, but that is a different beast)
